Feat/login form
SEAD-UFES/publications-frontend pull request #1
Opened 2018-05-25 21:53 UTC by israelhenrique

2018-05-28 13:39 UTC, edo9k approved these changes
Partindo da perspectiva de alguém que só usou React em tutoriais até hoje, por mim tá aprovado.

2018-05-28 13:39 UTC, edo9k commented on src/components/form/form.js
> +  handleUsernameChange = (value) => {
Possível confusão entre `Username` e `UserName` (acho que o segundo caso é mais intuitivo como nome, não se é padrão no React usar Username)

2018-05-28 13:39 UTC, edo9k commented on src/components/button/button.js
> +}) => (<button type={type} className={`btn btn-${className}`} onClick={onClick}>{children}</button>)
Esse `btn` é padrão entre bibliotecas de componente ou já está assumindo que vamos usar **Bootstrap** ou uma biblioteca parecida?

2018-05-28 13:49 UTC, israelhenrique commented on src/components/form/form.js
> +  handleUsernameChange = (value) => {
Eu coloquei `Username` para se referir a palavra única `Username`, para não confundir com `User Name` que seria escrito como `UserName`. Discorda desta abordagem?

2018-05-28 13:51 UTC, israelhenrique commented on src/components/button/button.js
> +}) => (<button type={type} className={`btn btn-${className}`} onClick={onClick}>{children}</button>)
Estou usando **Bootstrap** e achei interessante usar forma padrão dele de nomear as classes. Acho que podemos manter a nomeclatura mesmo se mudarmos a framework. O que acha? Tem alguma sugestão de outra padronização?

2018-05-28 15:33 UTC, josmardias requested changes
O código parece ótimo, apenas algumas sugestões para melhorar o estilo de formatação, organização do código.

Há também uma dica sobre melhorar os tests.

2018-05-28 15:33 UTC, josmardias commented on src/components/button/button.story.js
> +import * as React from 'react'
`import React from 'react'`

2018-05-28 15:33 UTC, josmardias commented on src/components/button/button.js
> +export const Primary = ({ type, onClick, children }) => <Button type={type} onClick={onClick}  className="primary">{children}</Button>
recomendo usar multiline na definição dos components, por dois principais motivos:
1) legibilidade
2) evitar conflitos de git: no caso do `single line` todas mudanças feitas em duas branchs em paralelo acarretará conflito. Enquanto em multiline só terá conflito se as mudanças forem na mesma linha.

Sugestão de formatação:
```jsx
export const Primary = ({ type, onClick, children }) => (
  <Button
    type={type}
    onClick={onClick}
    className="primary"
  >
      {children}
  </Button>
)
```

---

o mesmo vale para todos os outros components

---

existem [regras no eslint](https://github.com/yannickcr/eslint-plugin-react) que podem ajudar obrigar esse tipo de formatação, caso tenha interesse em investir tempo nisso

2018-05-28 15:33 UTC, josmardias commented on src/components/button/button.js
> +}) => (<button type={type} className={`btn btn-${className}`} onClick={onClick}>{children}</button>)
Recomendo utilizar `type="button"` por padrão
`button` sem type é `submit` por default
http://lea.verou.me/2018/05/never-forget-typebutton-on-generated-buttons/

2018-05-28 15:33 UTC, josmardias commented on src/components/text/text.css
> +}
é uma boa prática sempre ter um [EOF](https://pt.wikipedia.org/wiki/EOF)
nunca se sabe quando algum programa vai chorar por causa da ausência do mesmo
![image](https://user-images.githubusercontent.com/413430/40620847-bdffceac-6270-11e8-9e1a-c979aeca5009.png)

2018-05-28 15:33 UTC, josmardias commented on src/components/input/input.test.js
> +    expect(inputPassword.find({ name: inputPasswordProps.name })).toHaveLength(1)
eu acho bacana colocar o `find` em sua propria linha, armazenando em uma variavel
assim o `expect` fica mais legível

exatamente como você fez em `test change event`

2018-05-28 15:33 UTC, josmardias commented on src/components/input/input.test.js
> +  test('test change event', () => {
esse nome de test não está muito legal
não precisa avisar que é um test, pois é contextual
recomendo colocar o que se espera que aconteça
sugstão: `should call prop when input changes`

2018-05-28 15:33 UTC, josmardias commented on src/components/form/form.test.js
> +  test('test submit event', () => {
mensagem de test não precisa avisar que é um test, pois é uma informação contextual
sugestão: `should call prop when internal form submit`

2018-05-28 15:33 UTC, josmardias commented on src/components/form/form.test.js
> +  })
acho bacana colocar new line entre os tests

2018-05-28 15:33 UTC, josmardias commented on src/components/input/input.test.js
> +    inputText = shallow(<Input.Text {...inputTextProps}/>)
Você está utilizando uma abordagem `blackbox`, onde você testa sem se preocupar com a implementação interna de cada component.
Um ponto positivo é que você tem uma assertividade maior: você consegue ter certeza que seus components funcionam, não confiando cegamento no component interno `Input.Input`
Já um ponto negativo dessa abordagem é que você acaba tendo muito copy+paste de testes no seu projeto (cada novo Input que sugir você repetirá a mesma dose de testes). Já se observa as repetições para os components `Input.Text` e `Input.Password`.

Quando fazer `whitebox` (testar a implementação) e quando fazer `blackbox` (testar o funcionamento)?
É uma questão muito sensível, que acho que não tem uma resposta absoluta.
Porém, eu tenho um módus operandi que pode ser aplicado aqui, então vou deixar a sugestão:
- Faça teste blackbox o comportamento testado depende de comportamento de component externo ao projeto.
- Faça teste whitebox se você não depende de comportamento externo, ou se depende de componente interno que já é testado.

Em outras palavras, você poderia exportar e testar `Input.Input` com essa mesma bateria de testes que você fez (`blackbox`, pois depende de `<input />` funcionar) . Já nos testes do `Input.Text` `Input.Password` você testa `whitebox`, ou seja, apenas verifica se eles renderizam um `Input.Input` passando as props corretamente.
Assim você terá um set bem mais limitado de testes que será repetido, diminuindo problemas devido ao copy/paste.

---

Ah, se possível coloca cada component em seu próprio arquivo, e um arquivo de teste exclusivo para cada component :dancer:

2018-05-28 18:08 UTC, israelhenrique commented on src/components/input/input.test.js
> +    inputText = shallow(<Input.Text {...inputTextProps}/>)
Gostei bastante desta sugestão. Eu já estava ficando incomodado com a repetição de código de teste.

2018-06-06 17:32 UTC, josmardias requested changes
As últimas mudanças parecem ok
Falta só a questão do test do `<Input.* />`
e consertar a label de dois tests que está escrito `test click event` em vez de `should ...`

2018-06-07 16:02 UTC, josmardias requested changes
Só falta a questão do test do <Input.* />

2018-06-14 20:22 UTC, merged